branches:
  only:
    - master
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
install:
  - choco install graphviz
  - SET JAVA_HOME=C:\Program Files\Java\jdk11
build_script:
  - gradlew build -x test
test_script:
  - cmd: gradlew test || exit /B 0
after_test:
  - ps: >-
      $wc = New-Object "System.Net.WebClient"

      Get-ChildItem -Recurse | where { $_.Name -match "TEST-*.xml" } |
      Foreach-Object {
          $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_.FullName))
      }
artifacts:
  - path: build/test-results
