name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - run: ./gradlew build
      - name: upload test report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: app/build/reports/tests/test
