name: GitHubPackagesにdeployする
on:
  push:
    tags:
      - '*'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: publish
        env:
          USERNAME: ${{ github.repository_owner }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF: ${{ github.ref }}
        run: |
          export VERSION=${REF##*/}
          export REPOSITORY_URL=https://maven.pkg.github.com/${GITHUB_REPOSITORY}
          ./gradlew publish
